openapi: 3.0.1
info:
  title: WSO2 API Manager - CTL Artifact Converter API
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - **Artifact Converter API**.
  contact:
    name: WSO2
    url: https://wso2.com/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: https://apis.wso2.com/api/am/ctl-artifact-converter/v1
paths:
  ######################################################
  # The "API Collection" resource APIs
  ######################################################
  /artifact-convert:
    post:
      tags:
        - Convert Artifact
      summary: |
        Convert export API or API Product artifacts from one version to another
      description: |
        This operation allows to convert CTL artifacts from one version to another.
        
        Note : As of now only 3.2.0 to 4.2.0 conversion is supported.
      parameters:
        - $ref: '#/components/parameters/srcVersion'
        - $ref: '#/components/parameters/targetVersion'
        - $ref: '#/components/parameters/exportFormat'
        - $ref: '#/components/parameters/type'
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              properties:
                file:
                  type: string
                  description: Zip archive consisting of export artifact from source version
                  format: binary
      responses:
        200:
          description: |
            OK.
            Converted artifact binary is returned.
          headers:
            Content-Type:
              description: The content type of the body.
              schema:
                type: string
          content:
            application/zip:
              schema:
                type: string
                format: binary
        500:
          $ref: '#/components/responses/InternalServerError'
      operationId: convertCTLArtifact

components:
  schemas:
    Error:
      title: Error object returned with 4XX HTTP Status
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
          description: Error message.
        description:
          type: string
          description: |
            A detail description about the error message.
        moreInfo:
          type: string
          description: |
            Preferably an url with more details about the error.
        error:
          type: array
          description: |
            If there are more than one error list them out.
            For example, list out validation errors by each field.
          items:
            $ref: '#/components/schemas/ErrorListItem'
    ErrorListItem:
      title: Description of individual errors that may have occurred during a request.
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
          description: |
            Description about individual errors occurred
        description:
          type: string
          description: |
            A detail description about the error message.
  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 500
            message: Internal Server Error
            description: The server encountered an internal error. Please contact
              administrator.
            moreInfo: ""
            error: []
  parameters:
    srcVersion:
      name: srcVersion
      in: query
      description: |
        Source artifact version
      schema:
        type: string
        enum:
          - 3.2.0
        default: '3.2.0'
    targetVersion:
      name: targetVersion
      in: query
      description: |
        Target artifact version
      schema:
        type: string
        enum:
          - 4.2.0
        default: '4.2.0'
    exportFormat:
      name: exportFormat
      in: query
      description: |
        Export artifact format (YAML or JSON)
      schema:
        type: string
        enum:
          - YAML
          - JSON
        default: 'YAML'
    type:
      name: type
      in: query
      description: |
        Export artifact type (API or APIProduct)
      schema:
        type: string
        enum:
          - API
          - APIProduct
        default: 'API'
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apim:artifact_migrate: Migrate API Artifact